name: bloc_example
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

  #Route
  auto_route: ^7.8.4

  # UI
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6

  # Service
  dio: ^5.4.1

  #Core
  easy_localization: ^3.0.4
  equatable: ^2.0.5

  # Firebase
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8

  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.4
  flutter_gen_runner: ^5.4.0
  
  # Code Generation
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

  # Dependency Injection
  get_it: ^7.6.7

  # Google
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  google_sign_in_ios: ^5.7.4
  json_annotation: ^4.8.1

  # Utility
  kartal: ^3.5.0
  logger: ^2.0.2+1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  auto_route_generator: ^7.3.2

  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

  # Linting
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/gen
  line_length: 80
  flutter_svg: true
  lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml
  assets:
    inputs:
      - assets/images/
      - assets/icons/

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/colors/colors.xml
    - assets/icons/
